name: invoice_app
description: Invoice App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  auto_route: ^5.0.0
  cached_network_image: ^3.2.1
  dartz: ^0.10.1
  dio: ^4.0.6
  flash: ^2.0.3+3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_secure_storage: ^6.0.0
  freezed_annotation: ^2.1.0
  hooks_riverpod: ^1.0.4
  http: ^0.13.5
  json_annotation: ^4.6.0
  material_design_icons_flutter: ^5.0.6996
  oauth2: ^2.0.0
  path: ^1.8.1
  path_provider: ^2.0.11
  sembast: ^3.2.0+1
  shimmer: ^2.0.0
  webview_flutter: ^3.0.4
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  auto_route_generator: ^5.0.0
  lint: ^1.10.0
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/
    - asset/font/
    - asset/image/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Spartan
      fonts:
        - asset: asset/font/Spartan-Black.ttf
        - asset: asset/font/Spartan-Bold.ttf
        - asset: asset/font/Spartan-ExtraBold.ttf
        - asset: asset/font/Spartan-ExtraLight.ttf
        - asset: asset/font/Spartan-Light.ttf
        - asset: asset/font/Spartan-Medium.ttf
        - asset: asset/font/Spartan-Regular.ttf
        - asset: asset/font/Spartan-SemiBold.ttf
        - asset: asset/font/Spartan-Thin.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages